language: node_js

node_js:
  - "10"
  - "12"

sudo: false

matrix:
  include:
    - node_js: "12"
      env: TEST_SUITE=lint

cache:
  directories:
    - node_modules

install:
  - yarn

script:
  - if [ "$TEST_SUITE" == "lint" ]; then yarn run lint; else yarn run test:all; fi
